### ISSUE TITLE
Add a google/duckduckgo search

### ISSUE THREAD

**Issue by michael-beaver** [project-salsa/jar-of-salsa#4]
Like some other bots I've seen, I think it would be really cool to have a google or duckduckgo search option that just returns a link to the first search result that comes up in a search with the passed parameters. If integrated with duckduckgo, I would especially like to be sure that there is a way to integrate the `!` searches

**Comment by renodubois** [comment]
Added in https://github.com/project-salsa/jar-of-salsa/commit/2892a61ef5ec5919aeab64cbeaeb8805cc655a80, closing this
